### ISSUE TITLE
StringIndexOutOfBoundsException: String index out of range: 37

### ISSUE THREAD

**Issue by yegor256** [cqfn/jpeek#538]
```
Exception in thread "main" java.io.UncheckedIOException: java.io.IOException: java.util.concurrent.ExecutionException: java.lang.StringIndexOutOfBoundsException: String index out of range: 37
	at org.cactoos.scalar.Unchecked.value(Unchecked.java:58)
	at org.jpeek.skeleton.Skeleton.packages(Skeleton.java:153)
	at org.jpeek.skeleton.Skeleton.xml(Skeleton.java:113)
	at org.jpeek.App.analyze(App.java:148)
	at org.jpeek.Main.run(Main.java:152)
	at org.jpeek.Main.main(Main.java:125)
Caused by: java.io.IOException: java.util.concurrent.ExecutionException: java.lang.StringIndexOutOfBoundsException: String index out of range: 37
	at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:56)
	at org.cactoos.scalar.Checked.value(Checked.java:76)
	at org.cactoos.scalar.IoChecked.value(IoChecked.java:63)
	at org.cactoos.scalar.Unchecked.value(Unchecked.java:56)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:57)
	at org.cactoos.scalar.Checked.wrappedException(Checked.java:100)
	at org.cactoos.scalar.Checked.value(Checked.java:85)
	at org.cactoos.scalar.IoChecked.value(IoChecked.java:63)
	at org.cactoos.scalar.Unchecked.value(Unchecked.java:56)
	... 5 more
Caused by: java.util.concurrent.ExecutionException: java.lang.StringIndexOutOfBoundsException: String index out of range: 37
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.cactoos.scalar.And.lambda$null$0(And.java:97)
	at org.cactoos.scalar.ScalarEnvelope.value(ScalarEnvelope.java:53)
	at org.cactoos.scalar.And.value(And.java:152)
	at org.cactoos.scalar.AndInThreads.value(AndInThreads.java:229)
	at org.cactoos.scalar.AndInThreads.value(AndInThreads.java:57)
	at org.cactoos.scalar.Checked.value(Checked.java:76)
	... 7 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 37
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:47)
	at java.base/java.lang.String.charAt(String.java:693)
	at org.objectweb.asm.signature.SignatureReader.accept(SignatureReader.java:110)
	at org.jpeek.skeleton.TypesOf.iterator(TypesOf.java:82)
	at org.xembly.Directives.toCollection(Directives.java:562)
	at org.xembly.Directives.append(Directives.java:228)
	at org.jpeek.skeleton.XmlClass.visitMethod(XmlClass.java:186)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1353)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:744)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
	at org.jpeek.skeleton.XmlClass.iterator(XmlClass.java:89)
	at org.xembly.Directives.toCollection(Directives.java:562)
	at org.xembly.Directives.append(Directives.java:228)
	at org.jpeek.skeleton.Skeleton.xembly(Skeleton.java:192)
	at org.jpeek.skeleton.Skeleton.lambda$packages$2(Skeleton.java:149)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by johnnywiller** [comment]
Do you have a Minimal Reproducible Example for this?

**Comment by pnatashap** [comment]
can have the same reason as https://github.com/cqfn/jpeek/issues/535 or java 20+

**Comment by yegor256** [comment]
@rultor release, tag is `0.32.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.32.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.32.3`

**Comment by yegor256** [comment]
@rultor stop
